version: "3"
services:
  json1:
    build: ./app_to_json
    ports:
      - "5001:5000"

  json2:
    build: ./app_to_json
    ports:
      - "5002:5000"

  json3:
    build: ./app_to_json
    ports:
      - "5003:5000"

  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    depends_on:
      - json1
      - json2
      - json3
